version: '3.8'

services:
  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: tfm_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: lzPostgre00
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build: .
    container_name: app_container
    volumes:
      - ./src:/app  # Monta el directorio src en /app dentro del contenedor
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://postgres:lzPostgre00@db:5432/tfm_db"
    networks:
      - app_network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  app_network:
    driver: bridge
  
volumes:
  postgres_data:
